# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65bafbfb68345f6e5dcc44f377a03a95232da5eb9539616088bd5719a320161895464f040ea8a7c66f899e997c4cbeda9b46a8a3058f557ec22436f1288b7818

test:
  secret_key_base: 74f58af58180b051a7534cfd936b8dba1298006a23aa7619645dc0a265f7fa525018f63815cbcd431c2e9deb90b97823b07ec8d742a2c6847d4d04d7979ab894

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
